image: python:3.7

stages:
  - build

build:
  image: docker:git
  services:
    - docker:dind
  stage: build
  script:
    - docker build -t Dockerfile .
    - docker push Dockerfile
  only:
    - master
