stages:
  - build
  - push

build:
  image: docker:git
  services:
    - docker:dind
  stage: build
  before_script:
    - docker login -u armin_gm -p khalepirezan registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/armin_gm/asd_project_98_6 .
    - docker push registry.gitlab.com/armin_gm/asd_project_98_6
  only:
    - master
push_to_heroku:
  image: docker:latest
  stage: push
  services:
  - docker:dind
  script:
    # This is for gitlab
    - docker login -u armin_gm -p khalepirezan registry.gitlab.com
    - docker pull  registry.gitlab.com/armin_gm/asd_project_98_6:latest
    # This is for heroku
    - docker login --username=arminbehnamnia@gmail.com  --password=200dbffa-6a11-46fb-963b-ab85e3c516f2 registry.heroku.com
    - docker tag registry.gitlab.com/armin_gm/asd_project_98_6:latest registry.heroku.com/makan-system/web:latest
    - docker push registry.heroku.com/makan-system/web:latest

