image: python:3.7

stages:
  - build
  - deploy

build:
  image: docker:git
  services:
    - docker:dind
  stage: build
  before_script:
    - docker login -u armin_gm -p khalepirezan registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/armin_gm/asd_project_98_6 .
    - docker push registry.gitlab.com/armin_gm/asd_project_98_6
  only:
    - master
staging:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-python-test-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
