stages:
  - test
  - build
  - push
tests:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  before_script:
    - docker login -u armin_gm -p khalepirezan registry.gitlab.com
  script:
    - docker build .
    - docker run python ./Code/manage.py test registration
  when: on_success
build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script:
    - docker login -u armin_gm -p khalepirezan registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/armin_gm/asd_project_98_6 .
    - docker push registry.gitlab.com/armin_gm/asd_project_98_6
push_to_heroku:
  image: docker:latest
  stage: push
  services:
  - docker:dind
  script:
    # This is for gitlab
    - docker login -u armin_gm -p khalepirezan registry.gitlab.com
    - docker pull  registry.gitlab.com/armin_gm/asd_project_98_6:latest
    # This is for heroku
    - docker login --username=arminbehnamnia@gmail.com  --password=72f0a6e9-6870-4aae-a725-8bf26fbfad42 registry.heroku.com
    - docker tag registry.gitlab.com/armin_gm/asd_project_98_6:latest registry.heroku.com/makan-system/web:latest
    - docker push registry.heroku.com/makan-system/web:latest

