image: python:3.7

stages:
  - build

build:
  image: docker:git
  services:
    - docker:dind
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - docker login -u armin_gm
    - docker build -t asd_project_98_6 .
    - docker push asd_project_98_6
  only:
    - master
