# Generated by Django 2.2.1 on 2019-06-07 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('accommodation_type', models.CharField(choices=[('هتل', 'هتل'), ('اقامتگاه', 'اقامتگاه'), ('منزل شخصی', 'منزل شخصی')], max_length=20)),
                ('province', models.CharField(default='تهران', max_length=30)),
                ('city', models.CharField(default='تهران', max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bed_type', models.CharField(choices=[('Single', 'تخت یک نفره'), ('Double', 'تخت دو نفره'), ('Twin', 'دو تخت یک نفره')], max_length=20)),
                ('number_of_guests', models.IntegerField()),
                ('image', models.ImageField(upload_to='../media/room_pics/')),
                ('how_many', models.IntegerField(default=1)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.Accommodation')),
                ('amenity', models.ManyToManyField(to='accommodation.Amenity')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='../media/house_pics/')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.Accommodation')),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='amenity',
            field=models.ManyToManyField(to='accommodation.Amenity'),
        ),
    ]
