# Generated by Django 2.2.1 on 2019-05-21 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190521_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 21, 6, 57, 22, 407001)),
        ),
        migrations.AlterField(
            model_name='host',
            name='passport_pic',
            field=models.ImageField(default='../media/profile_pics/no-picture.png', upload_to='../media/passport_pics/'),
        ),
    ]
